engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/TrailingBlankLines:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
ratings:
  paths:
  - lib/**
exclude_paths:
- apps/*
- spec/**/*
- ideas/**/*
- examples/**/*
- README.md

