language: ruby
rvm:
- "2.2.2"
before_install: gem install bundler -v 1.10.5
script: bundle exec rake test
addons:
  code_climate:
    repo_token: 5059582f177ecb9cd186cd5f939e2c26b14eacc41363595bf2b627eacad1c596